language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: IeGhzw/uCdZkLC9w7PZRJLp/msE3NUfJjHiOvK8wC0q6LjYFQ1hgOQ20pkav7UBA/RtAADNMOxhrPH/QHfta+szvsJ8tCC1F9jZ4s78rR/5bpa2SaOhg0Wez62bDMDJNGvT3vMGMaIIpCQXcmYxDqEEL5EyRqC1O2cYVGT4s6bUVJftxQ7CEzbwitGXvUsG0+IxcpCujKs0Ha98jnXcbMVOnG45B8H7tSi3oYApiKWURP8AbvYCQgtVaF6OhP5bDynue5y9/1rMO1OH10V6V8KM0eel1JUZ5IXL3oPYmnQnuHERlvaCDfjryX5FFYqO+76f/rl8he0vKUMge+SQceiLSjmiXayKZuKd91wlpSrtaTdDUOUCQbtOo5Q917fS8R7lEfcd5VgMhhfvaer6JJ+bYR3HW7lc12Ys37xJgviBlnJGsiQKiM1dnIOvLpCJDRRiwZM5v0kCWyf/4mr7r0H4mjD7aOmS3X/CUtoQBBQH79Ow5SiAGSi/GStG154ZDK+hIGDL2lghBGUzIBQcapKhGVitYc5cs1tcJKIl4Vacw3q0sFEPNJfrkwP/8Km9WsT5jeTXurOg+VRYEC1d39x41MVaFBNcGiyWxtmqoiJgH1H/fBJdzrlNQxxntXdrtX2IoIMG4mkVEcudhJqU8tMH9Qe7o8z/RBARe/zeG7GY=
